name: Build STLs

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      bases: "${{ steps.set-matrix.outputs.bases }}"
      bins: "${{ steps.set-matrix.outputs.bins }}"
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2

      - id: set-matrix
        run: |
          echo -n 'bases='  >> $GITHUB_OUTPUT
          cat params/Base.json | jq  -c -r '.parameterSets | keys '  >> $GITHUB_OUTPUT
          echo -n 'bins='  >> $GITHUB_OUTPUT
          cat params/Bin.json | jq  -c -r '.parameterSets | keys '  >> $GITHUB_OUTPUT

  bases:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pset: "${{ fromJSON(needs.setup.outputs.bases) }}"

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2

      - name: Checkout gridfinity repo
        uses: actions/checkout@master
        with:
          repository: kennetek/gridfinity-rebuilt-openscad
          path: gridfinity-rebuilt-openscad

      - name: Create output folder if needed
        run: |
          mkdir -p stls

      - uses: gpmidi/openscad-build-action@main
        with:
          input-file: gridfinity-rebuilt-openscad/gridfinity-rebuilt-baseplate.scad
          output-file: "stls/base-${{ matrix.pset }}.stl"
          customizer-parameter-file: "params/Base.json"
          customizer-parameter-set: "${{ matrix.pset }}"

      - uses: actions/upload-artifact@v4
        with:
          name: "base-${{ matrix.pset }}"
          path: "stls/base-${{ matrix.pset }}.stl"

  bins:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pset: "${{ fromJSON(needs.setup.outputs.bins) }}"

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2

      - name: Checkout gridfinity repo
        uses: actions/checkout@master
        with:
          repository: kennetek/gridfinity-rebuilt-openscad
          path: gridfinity-rebuilt-openscad

      - name: Create output folder if needed
        run: |
          mkdir -p stls

      - uses: gpmidi/openscad-build-action@main
        with:
          input-file: gridfinity-rebuilt-openscad/gridfinity-rebuilt-bins.scad
          output-file: "stls/bin-${{ matrix.pset }}.stl"
          customizer-parameter-file: "params/Bin.json"
          customizer-parameter-set: "${{ matrix.pset }}"

      - name: Slice & Dice
        uses: davidk/slic3r-action/gcode@master
        env:
          BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLICE_CFG: config.ini
          EXTRA_SLICER_ARGS: "--print-center 100,100 --output-filename-format {input_filename_base}_{printer_model}.gcode"
        with:
          args: "stls/bin-${{ matrix.pset }}.stl"

      - uses: actions/upload-artifact@v4
        with:
          name: "bin-${{ matrix.pset }}"
          path: |
            stls/bin-${{ matrix.pset }}.stl
