name: Test

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout gridfinity repo
        uses: actions/checkout@master
        with:
          repository: kennetek/gridfinity-rebuilt-openscad
          path: gridfinity-rebuilt-openscad
      - name: Move mobile app files to root
        run: |
          ls -alhR
          mkdir -p stls

      - uses: gpmidi/openscad-build-action@main
        with:
          input-file: gridfinity-rebuilt-openscad/gridfinity-rebuilt-baseplate.scad
          output-file: stls/test.stl
          customizer-parameter-file: params/Base.json
          customizer-parameter-set: '5x5'
      - uses: actions/upload-artifact@v4
        with:
          name: test-stl
          path: stls/test.stl
